version: 0.2

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Running maven clean for Customer Microservice
      - mvn -f mymarkcustomerapi/pom.xml clean
      - mvn -f mymarkcustomer/pom.xml clean
  build:
    commands:
      - echo Build started for Customer Microservice
      - mvn -f mymarkcustomerapi/pom.xml install -DskipTests
      - mvn -f mymarkcustomer/pom.xml install -DskipTests
      
  post_build:
    commands:
      - mv mymarkcustomer/target/mymarkcustomermicro.war mymarkcustomermicro.war
      - mkdir .ebextensions
      - mv mymarkcustomer/.ebextensions/* .ebextensions/

artifacts:
  files:
    - mymarkcustomermicro.war
    - .ebextensions/**/*
