version: 0.2

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Running maven clean
      - mvn install:install-file -Dfile=libs/mymarkshoppingcartapi.jar -DgroupId=com.mymark -DartifactId=mymarkshoppingcartapi -Dversion=0.0.1 -Dpackaging=jar
      - mvn -f mymarkcustomer/pom.xml clean
      - mvn -f mymarkcustomerapi/pom.xml clean
  build:
    commands:
      - echo Build started
      - mvn -f mymarkcustomerapi/pom.xml install -DskipTests
      - mvn -f mymarkcustomer/pom.xml install -DskipTests
      
  post_build:
    commands:
      - mv mymarkcustomer/target/mymarkcustomermicro.jar mymarkcustomermicro.jar

artifacts:
  files:
    - mymarkcustomermicro.jar
